.TH FFCFSTRESS 1 "March 8, 2009"
.SH NAME
ffcfstress \- constant force stress test for force-feedback devices
.SH SYNOPSIS
.B ffcfstress
[\-d <device>] [\-u <update rate>] [\-f <frequency>] [\-a <amplitude>]
[\-s <strength>] [\-o]

.SH "DESCRIPTION"
ffcfstress stress tests constant non-enveloped forces on a force feedback
device. It simulates a moving spring force by applying a frequently
updated constant force effect.

.B Beware, the stress test may damage your device!

.SH OPTIONS
At least one option is required.

.IP "\fB\-d\fR <\fIdevice\fR>"
The device to test (by default \fI/dev/input/event0\fR).

.IP "\fB\-u\fR <\fIupdate rate\fR>"
The update rate in Hz (25 by default).

.IP "\fB\-f\fR <\fIfrequency\fR>"
The spring center motion frequency in Hz (0.1 by default).

.IP "\fB\-a\fR <\fIamplitude\fR>"
The spring center motion amplitude, between 0.0 and 1.0 (1.0 by default).

.IP "\fB\-s\fR <\fIstrength\fR>"
The spring strength factor (1.0 by default).

.IP "\fB\-o\fR"
Dummy option, useful when all defaults should be used.

.SH SEE ALSO
\fBevtest\fP(1), \fBjstest\fP(1).

.SH AUTHOR
.B ffcfstress
was written by Oliver Hamann.

This manual page was written by Stephen Kitt <steve@sk2.org>, for the Debian
GNU/Linux system (but may be used by others). It was last modified for
.B ffcfstress
dated February 15, 2002.

