.TH FFMVFORCE 1 "March 8, 2009"
.SH NAME
ffmvforce \- force orientation test for force-feedback devices
.SH SYNOPSIS
.B ffmvforce
<device> [\-u <update rate>]

.SH "DESCRIPTION"
ffmvforce generates a force in a given direction, indicated by the
position of the mouse pointer in relation to the center of the tool's
window.

.B Beware, the stress test may damage your device!

.SH OPTIONS

.IP "\fR<\fIdevice\fR>"
The device to test.

.IP "\fB\-u\fR <\fIupdate rate\fR>"
The update rate in Hz (5 by default).

.SH SEE ALSO
\fBevtest\fP(1), \fBffcfstress\fP(1), \fBjstest\fP(1).

.SH AUTHOR
.B ffmvforce
was written by Oliver Hamann.

This manual page was written by Stephen Kitt <steve@sk2.org>, for the Debian
GNU/Linux system (but may be used by others). It was last modified for
.B ffmvforce
dated February 15, 2002.
